#pragma config(Motor,  port1,           TRL,           tmotorVex393_HBridge, openLoop, reversed)
#pragma config(Motor,  port2,           BRL,           tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           BRD,           tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port4,           FRD,           tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port7,           TLL,           tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port8,           BLL,           tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port9,           BLD,           tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          FLD,           tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX2)
#pragma competitionControl(Competition)
#include "Vex_Competition_Includes.c"

#include "parallelDrive.c"
#include "motorGroup.c"

#define liftUpBtn Btn5U
#define liftDownBtn Btn5D

parallel_drive drive;
motorGroup lift;

void pre_auton() {
	bStopTasksBetweenModes = true;

	initializeDrive(drive);
  setLeftMotors(drive, 2, FLD, BLD);
  setRightMotors(drive, 2, FRD, BRD);

  initializeGroup(lift, 4, TRL, BRL, TLL, BLL);
  configureButtonInput(lift, liftUpBtn, liftDownBtn, 15);
}

task autonomous() {
  AutonomousCodePlaceholderForTesting();
}

task usercontrol() {
	while (true) {
  	driveRuntime(drive);

  	takeInput(lift);
  }
}
