#pragma config(Motor,  port1,           TRL,           tmotorVex393_HBridge, openLoop, reversed)
#pragma config(Motor,  port2,           BRL,           tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           BRD,           tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port4,           FRD,           tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port7,           TLL,           tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port8,           BLL,           tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port9,           BLD,           tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          FLD,           tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

void setDrivePower(int left, int right) {
	motor[FRD] = right;
	motor[BRD] = right;
	motor[FLD] = left;
	motor[BLD] = left;
}

void setLiftPower(int power) {
	motor[BLL] = -power;
	motor[TLL] = -power;
	motor[BRL] = power;
	motor[TRL] = power;
}

task main()
{
	while (true) {
		setDrivePower(vexRT[Ch3], vexRT[Ch2]);

		setLiftPower(127*vexRT[Btn6U] - 127*vexRT[Btn6D]);
	}
}
