#pragma config(Sensor, dgtl1,  hungryHungry,   sensorDigitalOut)
#pragma config(Sensor, dgtl2,  hippo,          sensorDigitalOut)
#pragma config(Motor,  port1,           rbd,           tmotorVex393_HBridge, openLoop, reversed)
#pragma config(Motor,  port2,           lbd,           tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           lfd,           tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           rfd,           tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port5,           lift1,         tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port6,           lift2,         tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port7,           lift3,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           lift4,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,            ,             tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port10,           ,             tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX2)
#pragma competitionControl(Competition)
#include "Vex_Competition_Includes.c"

#include "buttonTracker.c"
#include "parallelDrive.c"
#include "motorGroup.c"

#define toggleMouthBtn Btn8U
#define toggleScoopBtn Btn8D
#define liftUpBtn Btn6U
#define liftDownBtn Btn6D

parallel_drive drive;
motorGroup lift;
motorGroup scoop;

void pre_auton() {
	bStopTasksBetweenModes = true;

	initializeDrive(drive);
  setLeftMotors(drive, 2, lfd, lbd);
  setRightMotors(drive, 2, rfd, rbd);

  initializeGroup(lift, 4, lift1, lift2, lift3, lift4);
  configureButtonInput(lift, liftUpBtn, liftDownBtn, 10);
}

task autonomous() {
  AutonomousCodePlaceholderForTesting();
}

task usercontrol() {
  while (true) {
    driveRuntime(drive);

    takeInput(lift);

    if (newlyPressed(toggleMouthBtn))
    	SensorValue[hungryHungry] = 1 - SensorValue[hungryHungry];

    if (newlyPressed(toggleScoopBtn))
    	SensorValue[hippo] = 1 - SensorValue[hippo];
  }
}
