#pragma config(Sensor, in2,    LeftPot,        sensorPotentiometer)
#pragma config(Sensor, dgtl1,  rightEncoder,   sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  leftEncoder,    sensorQuadEncoder)
#pragma config(Sensor, dgtl6,  clawPneu1,      sensorDigitalOut)
#pragma config(Sensor, dgtl7,  clawPneu2,      sensorDigitalOut)
#pragma config(Motor,  port1,           lbd,           tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           lfd,           tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           lift1,         tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port4,           lift2,         tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port5,           lift3,         tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port6,           lift4,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           lift5,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           lift6,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           rfd,           tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port10,          rbd,           tmotorVex393_HBridge, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX2)
#pragma competitionControl(Competition)
#include "Vex_Competition_Includes.c"

#include "parallelDrive.c"
#include "pd_autoMove.c"
#include "motorGroup.c"
#include "buttonTracker.c"

#define toggleClawBtn Btn6U
#define liftUpBtn Btn5U
#define liftDownBtn Btn5D
#define liftTopBtn Btn7U
#define liftBottomBtn Btn7D

#define liftMax 2650
#define liftMin 1100

motorGroup lift;

void pre_auton() {
  bStopTasksBetweenModes = true;

  initializeDrive(drive);
  setDriveMotors(drive, 4, lfd, lbd, rfd, rbd);
  attachEncoder(drive, leftEncoder, LEFT, 4);
  attachEncoder(drive, rightEncoder, RIGHT);

  initializeGroup(lift, 6, lift1, lift2, lift3, lift4, lift5, lift6);
  configureButtonInput(lift, liftUpBtn, liftDownBtn, 10, 127, -90);
  addSensor(lift, LeftPot);
  createTarget(lift, liftMax, liftTopBtn);
  createTarget(lift, liftMin, liftBottomBtn);
}

task autonomous() {
	driveStraight(24);
	turn(-90);
  //AutonomousCodePlaceholderForTesting();
}

task usercontrol() {
  while (true) {
    driveRuntime(drive);

    takeInput(lift);

    if (newlyPressed(toggleClawBtn)) {
    	SensorValue[clawPneu1] = 1 - SensorValue[clawPneu1];
    	SensorValue[clawPneu2] = SensorValue[clawPneu1];
    }
  }
}
