#pragma config(Motor,  port1,           rightFront,    tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           rightBack,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           toprightLift,  tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           bottomrightLift, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           clawRight,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           clawLeft,      tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port7,           bottomleftLift, tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port8,           topleftLift,   tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port9,           leftFront,     tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port10,          leftBack,      tmotorVex393_HBridge, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX2)
#pragma competitionControl(Competition)
#include "Vex_Competition_Includes.c"

#include "parallelDrive.c"
#include "motorGroup.c"

#define clawInBtn Btn6U
#define clawOutBtn Btn6D
#define clawStillSpeed 15

parallel_drive drive;
motorGroup lift;
motorGroup claw;

void pre_auton() { bStopTasksBetweenModes = true; }

task autonomous() {
  AutonomousCodePlaceholderForTesting();
}

bool clawClosed = false;

task usercontrol() {
  initializeDrive(drive);
  setLeftMotors(drive, 2, lfd, lbd);
  setRightMotors(drive, 2, rfd, rbd);

  initializeGroup(lift, 4, lift1, lift2, lift3, lift4);
  configureButtonInput(lift, Btn5U, Btn5D, 10, 127, -80);

  initializeGroup(claw, 2, claw1, claw2);

  while (true) {
    driveRuntime(drive);

    takeInput(lift);

    if (vexRT[clawInBtn] == 1) {
      clawClosed = true;
      setPower(claw, 127);
    } else if (vexRT[clawOutBtn] == 1) {
      clawClosed = false;
      setPower(claw, -127);
    } else {
      setPower(claw, clawClosed ? clawStillSpeed : 0);
    }
  }
}
