#pragma config(Sensor, in1,    liftPot,        sensorPotentiometer)
#pragma config(Sensor, dgtl1,  claw1,          sensorDigitalOut)
#pragma config(Sensor, dgtl2,  claw2,          sensorDigitalOut)
#pragma config(Motor,  port1,           rightFront,    tmotorVex393_HBridge, openLoop, reversed)
#pragma config(Motor,  port2,           rightBack,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           toprightLift,  tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           bottomrightLift, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           bottomleftLift, tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port8,           topleftLift,   tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port9,           leftFront,     tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port10,          leftBack,      tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX2)
#pragma competitionControl(Competition)
#include "Vex_Competition_Includes.c"

#include "parallelDrive.c"
#include "motorGroup.c"

#define openClawBtn Btn6U
#define closeClawBtn Btn6D
#define liftUpBtn Btn5U
#define liftDownBtn Btn5D
#define liftTopBtn Btn7U
#define liftBottomBtn Btn7D

#define liftMax 3000
#define liftMin 2150
#define liftAbsMin 1900
#define liftMiddle 2300

#define stillSpeedMagnitude 10

parallel_drive drive;
motorGroup lift;

void setClawState(bool val) {
	SensorValue[claw1] = val;
  SensorValue[claw2] = val;
}

void pre_auton() {
  bStopTasksBetweenModes = true;

  initializeDrive(drive, false, 20, 10, 1, 120);
  setLeftMotors(drive, 2, leftFront, leftBack);
  setRightMotors(drive, 2, rightFront, rightBack);

  initializeGroup(lift, 4, toprightLift, bottomrightLift, topleftLift, bottomleftLift);
  configureButtonInput(lift, liftUpBtn, liftDownBtn, stillSpeedMagnitude, 127, -80);
  addSensor(lift, liftPot, true);
  createTarget(lift, liftMax, liftTopBtn);
  createTarget(lift, liftMin, liftBottomBtn);
  //setAbsolutes(lift, liftAbsMin);
  lift.timeout = 65;
}

task autonomous() {
  AutonomousCodePlaceholderForTesting();
}

task usercontrol() {
	while (true) {
    driveRuntime(drive);

    lift.stillSpeed = stillSpeedMagnitude * (potentiometerVal(lift)>liftMiddle ? 1 : -1);
    takeInput(lift);

    if (vexRT[openClawBtn] == 1) {
    	setClawState(1);
    } else if (vexRT[closeClawBtn] == 1) {
    	setClawState(0);
    }
  }
}
