#pragma config(Sensor, dgtl1,  pneumaticSoul,  sensorDigitalOut)
#pragma config(Motor,  port1,           rbd,           tmotorVex393_HBridge, openLoop, reversed)
#pragma config(Motor,  port2,           lbd,           tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           lfd,           tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           rfd,           tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port5,           lift1,         tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port6,           lift2,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           lift3,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           lift4,         tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port9,           claw1,         tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port10,          claw2,         tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
#pragma platform(VEX2)
#pragma competitionControl(Competition)
#include "Vex_Competition_Includes.c"

#include "buttonTracker.c"
#include "parallelDrive.c"
#include "motorGroup.c"

#define toggleClawBtn Btn7U

parallel_drive drive;
motorGroup lift;
motorGroup claw;

void pre_auton() { bStopTasksBetweenModes = true; }

task autonomous() {
  AutonomousCodePlaceholderForTesting();
}

task usercontrol() {
  initializeDrive(drive);
  setLeftMotors(drive, 2, lfd, lbd);
  setRightMotors(drive, 2, rfd, rbd);

  initializeGroup(lift, 4, lift1, lift2, lift3, lift4);
  configureButtonInput(lift, Btn5U, Btn5D, 10);

  initializeGroup(claw, 2, claw1, claw2);
  configureButtonInput(claw, Btn6U, Btn6D, 5);

  while (true) {
    driveRuntime(drive);

    takeInput(lift);
    takeInput(claw);

    if (newlyPressed(toggleClawBtn)) SensorValue[pneumaticSoul] = 1 - SensorValue[pneumaticSoul];
  }
}
