#pragma config(Motor,  port1,           Seymore,       tmotorVex393_HBridge, openLoop, reversed)
#pragma config(Motor,  port2,           lfd,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           lbd,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           rbd,   tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port9,           rfd,   tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port10,          FeedMe,        tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//


#include "parallelDrive.c"
#include "motorGroup.c"

parallel_drive drive;
motorGroup feed;

task main() {
  initializeDrive(drive);
  setLeftMotors(drive, 2, lfd, lbd);
  setRightMotors(drive, 2, rfd, rbd);

  initializeGroup(feed, 2, Seymore, FeedMe);
  configureButtonInput(feed, Btn5U, Btn5D);

  while (true) {
    driveRuntime(drive);
    updatePosition(drive);

    takeInput(feed);

    if (vexRT[Btn6U] == 1) drive.width = calculateWidth(drive);

    if (vexRT[Btn6D] == 1) {
      setRobotPosition(drive, 0, 0, 0);
      resetGyro(drive);
    }
  }
}
