#pragma config(Motor,  port2,           lbd,           tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           lfd,           tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port8,           rbd,           tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           rfd,           tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "holonomicDrive.c"

holonomicDrive drive;

task main() {
	initializeDrive(drive, lfd, rfd, lbd, rbd);

	while (true) driveRuntime(drive);
}
