#pragma config(Motor,  port1,           ld,            tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           feedMe,        tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           seymour,       tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          rd,            tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "parallelDrive.c"
#include "motorGroup.c"

parallel_drive drive;
motorGroup feed;

void setup() {
	initializeDrive(drive);
	setLeftMotors(drive, 2, ld, rd);

	initializeGroup(feed, 2, feedMe, seymour);
	configureButtonInput(feed, Btn6U, Btn6D);
}

task main() {
	setup();

	while (true) {
		driveRuntime(drive);

		takeInput(feed);
	}
}
