#pragma config(Sensor, dgtl1,  pneumaticSoul,  sensorDigitalOut)
#pragma config(Motor,  port1,           rbd,           tmotorVex393_HBridge, openLoop, reversed)
#pragma config(Motor,  port2,           lbd,           tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           lfd,           tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           rfd,           tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port5,           lift1,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           lift2,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           lift3,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           lift4,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           claw1,         tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port10,          claw2,         tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main() {
	int liftPower, clawPower;

	while(true) {
		//claw pneunatics
		if (vexRT[Btn7U] == 1) {
			SensorValue[pneumaticSoul] = 1 - SensorValue[pneumaticSoul];
			while (vexRT[Btn7U] == 1) {}
		}

		//drive
		motor[lfd] = vexRT[Ch3];
		motor[lbd] = vexRT[Ch3];
		motor[rfd] = vexRT[Ch2];
		motor[rbd] = vexRT[Ch2];

		//lift
		liftPower = 127*vexRT[Btn5U] - 127*vexRT[Btn5D];
		motor[lift1] = liftPower;
		motor[lift2] = liftPower;
		motor[lift3] = liftPower;
		motor[lift4] = liftPower;

		//claw motors
		clawPower = 127*vexRT[Btn6U] - 127*vexRT[Btn6D];
		motor[claw1] = clawPower;
		motor[claw2] = clawPower;
	}
}
