#pragma config(Sensor, in1,    pot1,           sensorPotentiometer)
#pragma config(Sensor, in2,    pot2,           sensorPotentiometer)
#pragma config(Sensor, dgtl2,  lock,           sensorDigitalOut)
#pragma config(Motor,  port1,           rd1,           tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           rd2,           tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           lift1,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           lift2,         tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port5,           ld4,           tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           ld3,           tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           rd4,           tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           rd3,           tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port9,           ld2,           tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          ld1,           tmotorVex393_HBridge, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

int minus = 0;
int power = 127;

/*include "parallelDrive.c"

initializeDrive(drive);
setDriveMotors(drive, 4, ldrive, rdrive);
attachEncoder(drive, leftEnc, LEFT);
attachEncoder(drive, rightEnc, RIGHT, false, 4);*/





void usercontrol()
{

	while (1==1) {


//drive
		motor[ld1]  = (vexRT[Ch1] + vexRT[Ch2])/2;
		motor[ld2]  = (vexRT[Ch1] + vexRT[Ch2])/2;
		motor[rd1]  = (vexRT[Ch1] - vexRT[Ch2])/2;
		motor[rd2]  = (vexRT[Ch1] - vexRT[Ch2])/2;
	  motor[ld3] = (vexRT[Ch4] - vexRT[Ch3])/2;
	  motor[ld3] = (vexRT[Ch4] - vexRT[Ch3])/2;
	  motor[rd3] = (vexRT[Ch4] + vexRT[Ch3])/2;
	  motor[rd4] = (vexRT[Ch4] + vexRT[Ch3])/2;

//lift
		if (vexRT[Btn6U] == 1) {
			motor[lift1] = power;

		} else if (vexRT[Btn6D] == 1) {
			motor[lift1] = -power;

		} else {
			motor[lift1] = 15;

		}
			if (vexRT[Btn5U] == 1) {

			motor[lift2] = power;
		} else if (vexRT[Btn5D] == 1) {

			motor[lift2] = -power;
		} else {

			motor[lift2] = 15;
		}


	}
}
task main() {
	usercontrol();
}
