#pragma config(Sensor, dgtl1,  ASensor,        sensorDigitalOut)
#pragma config(Motor,  port1,           RTmotor,       tmotorVex393_HBridge, openLoop, reversed)
#pragma config(Motor,  port2,           RBmotor,       tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           RMmotorL,      tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port4,           RBmotorL,      tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port5,           RTmotorL,      tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port6,           LTmotorL,      tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port7,           LMmotorL,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           LBmotorL,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           LBmotor,       tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port10,          LTmotor,       tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#define stillSpeed 15

void setLiftPower(int power) {
	motor[RBmotorL] = power;
	motor[RMmotorL] = power;
	motor[RTmotorL] = power;
	motor[LBmotorL] = power;
	motor[LMmotorL] = power;
	motor[LTmotorL] = power;
}

void setDrivePower(int left, int right) {
	motor[RTmotor] = right;
	motor[RBmotor] = right;
	motor[LBmotor] = left;
	motor[LTmotor] = left;
}

task main()
{
	while (true)
  {
  	setDrivePower(vexRT[Ch3], vexRT[Ch2]);

		if (vexRT[Btn5U] == 1)
			{               //testing if the
			setLiftPower(127);                   //
		}
		else if (vexRT[Btn5D] == 1)
			{
			setLiftPower(-127);
		}
		else {
			setLiftPower(stillSpeed);  // So the lift system dosn't fall on its own, keeps constant force

		}

		// Pneumatic
			if (vexRT[Btn6U] == 1)
		{
			SensorValue[ASensor] = 1;
		}

				if (vexRT[Btn6D] == 1)
		{
			SensorValue[ASensor] = 0
		}
  }
}
