#pragma config(Sensor, in1,    ClawPent,       sensorPotentiometer)
#pragma config(Sensor, in2,    LiftPent,       sensorPotentiometer)
#pragma config(Sensor, dgtl1,  RightEnd1,      sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  LeftEnd1,       sensorQuadEncoder)
#pragma config(Motor,  port1,           RTmotorD,      tmotorVex393_HBridge, openLoop, reversed)
#pragma config(Motor,  port2,           RBmotorD,      tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           RBmotorL,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           RMmotorL,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           Claw,          tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           LandRTmotorL,  tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           LBmotorL,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           LMmotorL,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           LBmotorD,      tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port10,          LTmotorD,      tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#define stillSpeed -15

void setLiftPower(int power) {
	motor[RBmotorL] = power;
	motor[LandRTmotorL] = power;
	motor[LBmotorL] = power;
	motor[RMmotorL] = power;
	motor[LMmotorL] = power;

}

void setDrivePower(int left, int right) {
	motor[RTmotorD] = right;
	motor[RBmotorD] = right;
	motor[LBmotorD] = left;
	motor[LTmotorD] = left;
}

void setClawPower(int clawC){
	motor[Claw] = clawC;
}



task main()
{
	while (true)
  {
	  	setDrivePower(vexRT[Ch3], vexRT[Ch2]);

			if (vexRT[Btn5D] == 1)
				{               //testing if the
				setLiftPower(127);                   //
			}
			else if (vexRT[Btn5U] == 1)
				{
				setLiftPower(-127);
			}
			else {
				setLiftPower(stillSpeed);  // So the lift system dosn't fall on its own, keeps constant force
			}

				//claw
				if (vexRT[Btn6U] == 1)
				{
				setClawPower(127);
			}
			else if (vexRT[Btn6D] == 1)
				{
				setClawPower(-127);
			}
			else {
				setClawPower(0);
			}




			}
  }
