#pragma config(Sensor, dgtl1,  claw1,          sensorDigitalOut)
#pragma config(Sensor, dgtl2,  claw2,          sensorDigitalOut)
#pragma config(Motor,  port1,           rbd,           tmotorVex393_HBridge, openLoop, reversed)
#pragma config(Motor,  port2,           rfd,           tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           lift1,         tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port4,           lift2,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           claw1,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           claw2,         tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port7,           lift3,         tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port8,           lift4,         tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port9,           lfd,           tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          lbd,           tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX2)
#pragma competitionControl(Competition)
#include "Vex_Competition_Includes.c"

#include "..\Includes\parallelDrive.c"
#include "..\Includes\motorGroup.c"

#define openClawBtn Btn6U
#define closeClawBtn Btn6D
#define liftUpBtn Btn5U
#define liftDownBtn Btn5D

#define clawStillSpeed 15
short clawSign = 1;

parallel_drive drive;
motorGroup lift;
motorGroup claw;

bool clawOpen = true;

void pre_auton() {
  bStopTasksBetweenModes = true;

  initializeDrive(drive);
  setDriveMotors(drive, 4, lfd, lbd, rfd, rbd);

  initializeGroup(lift, 4, lift1, lift2, lift3, lift4);
  configureButtonInput(lift, liftUpBtn, liftDownBtn, 10, 127, -100);
  initializeGroup(claw, 2, claw1, claw2);
}

void clawControl() {
	if (vexRT[closeClawBtn] == 1) {
		setPower(claw, 127);
		clawSign = 1;
	} else if (vexRT[openClawBtn] == 1) {
		setPower(claw, -127);
		clawSign = -1;
	} else {
		setPower(claw, clawStillSpeed * clawSign);
	}
}

task autonomous() {
  AutonomousCodePlaceholderForTesting();
}

task usercontrol() {
	while (true) {
    driveRuntime(drive);

    takeInput(lift);

    clawControl();
  }
}
