#pragma config(Sensor, in1,    gyro,           sensorGyro)
#pragma config(Sensor, in2,    clawPotL,       sensorPotentiometer)
#pragma config(Sensor, in3,    clawPotR,       sensorPotentiometer)
#pragma config(Sensor, in4,    modePot,        sensorPotentiometer)
#pragma config(Sensor, in5,    liftPot,        sensorPotentiometer)
#pragma config(Sensor, dgtl1,  leftEnc,        sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  rightEnc,       sensorQuadEncoder)
#pragma config(Motor,  port1,           rbd,           tmotorVex393_HBridge, openLoop, reversed)
#pragma config(Motor,  port2,           rfd,           tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           lift1,         tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port4,           lift2,         tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port5,           lift3,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           clawMotor,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           lift4,         tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port8,           lift5,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           lfd,           tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          lbd,           tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//https://github.com/DHS-Robotics/Starstruck/blob/84a4a8a2bf6a746fdbcc648bd8628b1218530b2a/%24pneumaticSoul.c

//https://github.com/DHS-Robotics/Starstruck/blob/master/(G-team/(2131G.c
//OUR CODE'S LINK ON GITHUB

#pragma platform(VEX2)
#pragma competitionControl(Competition)
#include "Vex_Competition_Includes.c"

#include "..\Includes\parallelDrive.c"
#include "..\Includes\motorGroup.c"
#include "..\Includes\pd_autoMove.c"
#include "..\Includes\buttonTracker.c"

//Buttons
#define openClawBtn Btn6D
#define closeClawBtn Btn6U
#define liftUpBtn Btn5U
#define liftDownBtn Btn5D

//Positions
#define liftBottom 380
#define liftMax 2130
#define liftTop 1890
#define liftPush 1530
#define liftPushTop 1660

#define clawClosedPos 3920 //3595
#define clawOpenPos 2820
#define clawMax 778
#define clawPush 1990
#define clawClosedPosPillow 3305
#define clawClosedNew 1835 //??????
//*/


//Constants
#define liftStillSpeed 10
#define clawStillSpeed 15

//Varibles
bool clawOpen = false;
//short autoSign;

motorGroup lift;
motorGroup claw;

///////////////////////////////////////////////////////////////////////////////////////////////////////////

void pre_auton() { //INITIALIZATIONS
  bStopTasksBetweenModes = true;

  initializeDrive(drive);
  setDriveMotors(drive, 4, lfd, lbd, rfd, rbd);
  attachEncoder(drive, leftEnc, LEFT);
  attachEncoder(drive, rightEnc, RIGHT, false, 4);
  attachGyro(drive, gyro);

  initializeGroup(lift, 5, lift1, lift2, lift3, lift4, lift5); //USES MOTOR GROUP ARRAY IN INCLUDES
  configureButtonInput(lift, liftUpBtn, liftDownBtn, 10, 127, -100);
  setAbsolutes(lift, liftBottom, 0);
  addSensor(lift, liftPot);

  initializeGroup(claw, 1, clawMotor); //USES MOTOR GROUP ARRAY IN INCLUDES - Claw is only 1 motor
  addSensor(claw, clawPotL, false);
  addSensor(claw, clawPotR, false);

}

////////////////////////////////////////////////////////////////////////////////////////////////////////////

//BEGIN AUTON TAKEN FROM E - COMPLETELY CHANGED FROM E NOW
//autonomous region
void deploy(int waitAtEnd=250) { //THIS IS THE DEPLOY FUNCTION
	//deploy stops

	//OLD DEPLOY
	//goToPosition(lift, liftMax);
	//goToPosition(claw, clawMax, clawStillSpeed);
	//goToPosition(lift, liftBottom + 500);
	//goToPosition(claw, clawOpenPos);

  //driveStraight(10); //DRIVES FORWARD
  //driveStraight(-7); //TO MAKE GRAVITY LOWER THE CLAW

//setDrivePower(drive, 127, 127);
//wait1Msec(750);
//setDrivePower(drive, -127, -127);
//wait1Msec(1000);
//setDrivePower(drive, 0, 0);

//NEW DEPLOY FOR SOLID CLAW
	//driveStraight(3);
	setDrivePower(drive, 127, 127);
	wait1Msec(200);
	setDrivePower(drive, 0, 0);
	goToPosition(lift, liftBottom + 200, liftStillSpeed);
	goToPosition(claw, clawOpenPos, -clawStillSpeed);
	goToPosition(lift, liftBottom  + 30, liftStillSpeed);

}

//LETS THE CLAW BE ABLE TO OPEN AND CLOSE - CALLABLE FUNCTION
void setClawStateManeuver(bool open = !clawOpen) { //toggles by default
	if (open) {
		createManeuver(claw, clawOpenPos, -clawStillSpeed);
	} else {
		createManeuver(claw, clawClosedPos, -clawStillSpeed);
	}

	clawOpen = open;
}

void openClaw(bool stillSpeed=true) {
	goToPosition(claw, clawOpenPos, (stillSpeed ? clawStillSpeed : 0));  //OPEN CLAW FUNCTION
}

void closeClaw(bool stillSpeed=true) {
	goToPosition(claw, clawClosedPos, (stillSpeed ? -clawStillSpeed : 0)); //CLOSE CLAW FUNCTION
}

void hyperExtendClaw(bool stillSpeed=true) {
	goToPosition(claw, clawMax, (stillSpeed ? clawStillSpeed : 0)); //PUSHING VALUE - NOT CALLED
}

//AUTONOMOUSES ////////////////////////////////////////////////////////////////////////
//FIRST AUTON -> GRABS THE PILLOW, PUTS IT OVER, AND WILL PUSH OVER SOME JACKS
task pillowAutonRight() { //Put true to run 2 things at once

//VERY CHANGED FROM ORIGINAL, REFERENCE LEFT FOR MORE ORIGINAL ENCODER DRIVING, THERE IS A CURRENT PROBLEM WITH ENCODERS - MAY NEED TO JUST REDOWNLOAD FROM GITHUB

	//setClawStateManeuver(true); //open claw
  //goToPosition(lift, liftBottom, liftStillSpeed);
	//openClaw();
  //driveStraight(1); //drive away from wall
  //while(driveData.isDriving);






/*
  setDrivePower(drive, 127, 127);
	wait1Msec(1000);
	setDrivePower(drive, 0, 0);
	goToPosition(claw, clawClosedPosPillow, -clawStillSpeed);
	goToPosition(lift, liftBottom + 200, liftStillSpeed);
	setDrivePower(drive, 127, -127);
	wait1Msec(500);
	setDrivePower(drive, 0, 0);
	goToPosition(lift, liftTop, liftStillSpeed);
	setDrivePower(drive, 127, 127);
	wait1Msec(800);
	setDrivePower(drive, 0, 0);
	goToPosition(claw, clawOpenPos, -clawStillSpeed);
	setDrivePower(drive, -127, -127);
	wait1Msec(1300);
  setDrivePower(drive, 0, 0);
  goToPosition(lift, liftPush + 200, liftStillSpeed);
  goToPosition(claw, clawPush, -clawStillSpeed + 5);
  setDrivePower(drive, 127, 127);
  wait1Msec(1000);
  */






  //move toward pillow
//  turn(50.5, false, 40, 120, -40);
  //while(turnData.isTurning || claw.maneuverExecuting);
//  driveStraight(9);
/*
  goToPosition(claw, clawClosedPosPillow, -clawStillSpeed); //clamp pillow
  //closeClaw();
  goToPosition(lift, liftTop, liftStillSpeed);
  turn(30.5, false, 40, 120, -10);
  //--lift up--//
  driveStraight(13);
  //while (driveData.isDriving);
  //turn(0.4, false, 40, 80, -20); //turn to face fence
  //while (turnData.isTurning);
  driveStraight(5, true); // drive up to wall
  //while (driveData.isDriving || lift.maneuverExecuting); //Changed shoulder to lift; WORK?
  goToPosition(claw, clawOpenPos, -clawStillSpeed); //release pillow
  goToPosition(claw, clawPush, -clawStillSpeed);
  goToPosition(claw, clawClosedPos, -clawStillSpeed);
  driveStraight(-13); //back up
  //turn(15.5, false, 40, 120, -10);
  goToPosition(lift, liftPush, liftStillSpeed);
  //goToPosition(claw, clawPush, -clawStillSpeed);
  //push jacks over
 	driveStraight(13);
 	driveStraight(-14);
 	//goToPosition(claw, 900);
 	//Push off Stars
 	goToPosition(lift, liftPushTop, liftStillSpeed);
 	turn(30.5, false, 40, 120, -10);
 	driveStraight(15);
 	turn(-30.5, false, 40, 120, -10);
 	driveStraight(15);
 	closeClaw();
 	//createManeuver(claw, clawMax, clawStillSpeed); //hyperextend claw
 	//drive to other wall and lift down
 //	driveStraight(-5); //Put True if you want to perform two tasks at once
 	//while (driveData.isDriving);
 	//turn(63);
 	//while (turnData.isTurning || claw.maneuverExecuting);
 	//createManeuver(lift, liftMax, liftStillSpeed);
 	//driveStraight(43);
 	//while (driveData.isDriving || lift.maneuverExecuting);
 	//turn(-80, false, 40, 120, -40);
 	//driveStraight(7);
 	//goToPosition(lift, liftPush); //push jacks over
 	*/
}

////////////////////////////////////////////////////////////////////////////

//FIRST AUTON -> GRABS THE PILLOW, PUTS IT OVER, AND WILL PUSH OVER SOME JACKS BUT FROM OTHER SIDE OF THE FIELD
task pillowAutonLeft() { //Put true to run 2 things at once



setClawStateManeuver(true); //open claw
  //goToPosition(claw, clawOpenPos);
	goToPosition(claw, clawOpenPos, -clawStillSpeed);
  driveStraight(1); //drive away from wall
  //while(driveData.isDriving);

  //move toward pillow
  turn(50.5, false, 40, 120, -40);
  //while(turnData.isTurning || claw.maneuverExecuting);
  driveStraight(12.5);

  goToPosition(claw, clawClosedPosPillow, -clawStillSpeed); //clamp pillow
  //closeClaw();

  goToPosition(lift, liftTop, liftStillSpeed);

  turn(-30.5, false, 40, 120, -10);
  //while(turnData.isTurning);
  //goToPosition(lift, liftTop);

  //--lift up--//
  driveStraight(12);
  //while (driveData.isDriving);
  //turn(0.4, false, 40, 80, -20); //turn to face fence
  //while (turnData.isTurning);
  driveStraight(10, true); // drive up to wall
  //while (driveData.isDriving || lift.maneuverExecuting); //Changed shoulder to lift; WORK?

  goToPosition(claw, clawOpenPos, -clawStillSpeed); //release pillow
  closeClaw();
  driveStraight(-13); //back up
  //turn(15.5, false, 40, 120, -10);
  goToPosition(lift, liftPush, liftStillSpeed);
  goToPosition(claw, clawPush, -clawStillSpeed);

  //push jacks over
 	driveStraight(13);
 	driveStraight(-13);
 	//goToPosition(claw, 900);

 	//Push off Stars
 	goToPosition(lift, liftPushTop);
 	turn(-30.5, false, 40, 120, -10);
 	driveStraight(15);
 	turn(30.5, false, 40, 120, -10);
 	driveStraight(15);

 	//createManeuver(claw, clawMax, clawStillSpeed); //hyperextend claw

 	//drive to other wall and lift down
 //	driveStraight(-5); //Put True if you want to perform two tasks at once
 	//while (driveData.isDriving);
 	//turn(63);
 	//while (turnData.isTurning || claw.maneuverExecuting);
 	//createManeuver(lift, liftMax, liftStillSpeed);
 	//driveStraight(43);
 	//while (driveData.isDriving || lift.maneuverExecuting);
 	//turn(-80, false, 40, 120, -40);
 	//driveStraight(7);

 	//goToPosition(lift, liftPush); //push jacks over
}

////////////////////////////////////////////////////////////////////////////////////

 task programmingSkills() {

  //ONE SIDE AUTON
	//goToPosition(claw, clawPush, -clawStillSpeed);
	//goToPosition(lift, liftPushTop);
  //driveStraight(30); //drive away from wall

  ////////////////////////////////////////////////////////////////////////////////////

  //NEW SINGLE SIDE AUTON ^^^^^^^^^^^^^^

 /////////////////////////////////////////////////////////////////////////////////////


 goToPosition(lift, liftPushTop, liftStillSpeed);
 goToPosition(claw, clawPush, -clawStillSpeed + 5);
 setDrivePower(drive, 127, 127);
 wait1Msec(1800);
 setDrivePower(drive, 0, 0);


 /*
 //NEW BACK AUTON
 wait1Msec(2000);
 goToPosition(claw, clawOpenPos + 250, -clawStillSpeed);
 driveStraight(15);
 goToPosition(claw, clawClosedNew, -clawStillSpeed);
 goToPosition(lift, liftPushTop, liftStillSpeed);
 driveStraight(-18);
 turn(50, false, 40, 120, -40);
 driveStraight(15);
 goToPosition(claw, clawOpenPos, -clawStillSpeed);
  */

  /*
  //NEW AUTON FOR PROGRAMMING SKILLS
  setClawStateManeuver(true);
	goToPosition(claw, clawOpenPos, -clawStillSpeed); //Open The Claw
  driveStraight(1); //drive away from wall
  //move toward pillow
  turn(-50.5, false, 40, 120, -40);
  driveStraight(12.5);
  goToPosition(claw, clawClosedPosPillow, -clawStillSpeed); //Grab Pillow
  goToPosition(lift, liftTop); //Rise Lift
  //Angle to Wall
  turn(30.5, false, 40, 120, -10);
  driveStraight(13);
  driveStraight(10, true); // drive up to wall
  //Relase Claw and Prepare to Push
  goToPosition(claw, clawOpenPos, -clawStillSpeed); //release pillow
  goToPosition(claw, clawClosedPos, -clawStillSpeed);
  driveStraight(-10); //back up
  goToPosition(lift, liftPush, liftStillSpeed);
  goToPosition(claw, clawPush, -clawStillSpeed);
  //Push and Backup
 	driveStraight(12);
 	driveStraight(-20); //reverse from wall to turn
 	//Continue to Push off Stars
 	goToPosition(lift, liftPushTop, liftStillSpeed);
 	turn(-30.5, false, 40, 120, -10);
 	driveStraight(15);
 	turn(30.5, false, 40, 120, -10);
 	driveStraight(15);
 	driveStraight(-10); //reverse from wall to turn again
 	//Another Round Of Pushing Off Stars
 	turn(-30.5, false, 40, 120, -10);
 	driveStraight(15);
 	turn(30.5, false, 40, 120, -10);
 	driveStraight(15);
 	//Reverse To Try and Grab The Pillow and Drop It ****** NEEDS MAJOR TUNING
 	driveStraight(-5);
 	turn(175.5, false, 40, 120, -10);
 	goToPosition(lift, liftBottom, liftStillSpeed);
 	driveStraight(13);
 	goToPosition(claw, clawClosedPos, -clawStillSpeed);
 	driveStraight(-5);
 	turn(-90, false, 40, 120, -10);
 	goToPosition(lift, liftTop, liftStillSpeed);
 	driveStraight(30);
 	goToPosition(claw, clawOpenPos, -clawStillSpeed);
 	driveStraight(-15);
 	//*/
}

//////////////////////////////////////////////////////////////////////////////////////

task autonomous() {
	lift.maneuverExecuting = false;
	claw.maneuverExecuting = false;
	//startTask(maneuvers);

  deploy();

  //autoSign = (SensorValue[sidePot] < 1800) ? 1 : -1;

  //start appropriate autonomous task
  if (SensorValue[modePot] < 4095 && SensorValue[modePot] > 2700) {
  	startTask(pillowAutonLeft);
  } else if (SensorValue[modePot] < 2699 && (SensorValue[modePot] > 2000)) {
  	startTask(programmingSkills);
  } else if (SensorValue[modePot] < 1850) {
  	startTask(pillowAutonRight);
  }
}
//end autonomous region

////////////////////////////////////////////////////////////////////////////////////////////////////////////

void clawControl() {
	if (vexRT[closeClawBtn] == 1) {
		setPower(claw, 127);
		clawOpen = false;
	} else if (vexRT[openClawBtn] == 1) {
		setPower(claw, -127);
		clawOpen = true;
	} else {
		setPower(claw, clawStillSpeed * (clawOpen ? -1 : 1));
	}
}
//END OF AUTON TAKEN FROM E

/*task autonomous() {
  AutonomousCodePlaceholderForTesting();
}
*/

task usercontrol() {
	while (true) {
    driveRuntime(drive); //USES CLAW FUNCTION TO TAKE INPUTS

    takeInput(lift); //USES LIFT FUNCTIONS TO CONTROL LIFT

    clawControl(); //USES CLAW CONTROL FUNCTION TO CONTROL CLAW

    //TEST FOR PUSH BUTTON///////////////////////////////////////////////////

    if (vexRT[Btn8U] == 1) //GOES TO THE POSITION TO PUSH OF STARS OFF OF TOP
    {
    	goToPosition(lift, liftPushTop);
    	//goToPosition(claw, clawPush, clawStillSpeed);
    }
    if (vexRT[Btn8D] == 1) //GOES TO THE POSITION TO PUSH OF STARS OF MIDDLE
    {
    	goToPosition(lift, liftPush);
    	//goToPosition(claw, clawPush, clawStillSpeed);
    }

  }
}
