#pragma config(Sensor, in1,    gyro,           sensorGyro)
#pragma config(Sensor, in2,    lowLiftPot,     sensorPotentiometer)
#pragma config(Sensor, in3,    highLiftPot,    sensorPotentiometer)
#pragma config(Motor,  port5,           lowLift1,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           lowLift2,      tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port7,           highLift1,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           highLift2,     tmotorVex393_MC29, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

int stillSpeed = 10;
int middle = 2215;
int llss=1;
float hlss=0;

task main() {
	int mcoeff;

	while (true) {
		mcoeff = (SensorValue[lowLiftPot]<middle ? 1 : -1) * hlss;

		if (llss == 1) {
			motor[lowLift1] = mcoeff * stillSpeed;
			motor[lowLift2] = mcoeff * stillSpeed;
		} else {
			motor[lowLift1] = 0;
			motor[lowLift2] = 0;
		}

		motor[highLift1] = mcoeff * stillSpeed;
		motor[highLift2] = mcoeff * stillSpeed;
	}
}
