#pragma config(Sensor, in1,    arm,            sensorPotentiometer)
#pragma config(Sensor, in2,    driveSelect,    sensorPotentiometer)
#pragma config(Sensor, in3,    pinchL,         sensorPotentiometer)
#pragma config(Sensor, in4,    pinchR,         sensorPotentiometer)
#pragma config(Motor,  port1,           rClaw,         tmotorVex393TurboSpeed_HBridge, openLoop, reversed)
#pragma config(Motor,  port2,           LClaw,         tmotorVex393TurboSpeed_MC29, openLoop)
#pragma config(Motor,  port3,           Lift1,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           Lift2,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           Lift3,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           rDrive,        tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port7,           Lift4,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           Lift5,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           FL,            tmotorVex393TurboSpeed_MC29, openLoop)
#pragma config(Motor,  port10,          BL,            tmotorVex393TurboSpeed_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration  wizard               !!*//

#pragma platform(VEX2)

// Select Download method as "competition"
#pragma competitionControl(Competition)

//Main competition background code...do not modify!
#include "Vex_Competition_Includes.c"
//#include "BackOver Functions.c"
#include "..\Includes\PID.c"


PID clawPID_L;
PID clawPID_R;


void pre_auton() {
	bStopTasksBetweenModes = true;

	initializePID(clawPID_L, SensorValue[pinchL], 0.2, 0, 0.7, 25);
	initializePID(clawPID_R, SensorValue[pinchR], 0.2, 0, 0.7, 25);
}

task autonomous() { AutonomousCodePlaceholderForTesting(); }

task usercontrol()
{
	while (true)
	{

		motor[BL] = vexRT[Ch3];
		motor[FL] = vexRT[Ch3];
		motor[rDrive] = vexRT[Ch2];


		///// lift control /////////////////////////////////////////////////////////////////
	int liftStillSpeedSet;

		if( vexRT[Btn5U] == 1 )
		{
			motor[Lift1] = 127;
			motor[Lift2] = 127;
			motor[Lift3] = 127;
			motor[Lift4] = 127;
			motor[Lift5] = 127;
			liftStillSpeedSet=15;
		}

		else if( vexRT[Btn5D] == 1 )
		{
			motor[Lift1] = -127;
			motor[Lift2] = -127;
			motor[Lift3] = -127;
			motor[Lift4] = -127;
			motor[Lift5] = -127;
			liftStillSpeedSet=-15;
		}

		else
		{
			motor[Lift1] = liftStillSpeedSet;
			motor[Lift2] = liftStillSpeedSet;
			motor[Lift3] = liftStillSpeedSet;
			motor[Lift4] = liftStillSpeedSet;
			motor[Lift5] = liftStillSpeedSet;
		}

		//// pinch control /////////////////////////////////////////////////////////////////////////////////

		if( vexRT[ Btn6D ] == 1 )
		{
			clawPID_R.target = 400;
			clawPID_L.target = 400;
		}

		else if( vexRT[ Btn6U ] == 1)
		{
			clawPID_R.target = 1150;
			clawPID_L.target = 1150;
		}
		else if(vexRT[Btn7D] == 1)
		{
			clawPID_R.target = 2000;
			clawPID_L.target = 2000;
		}

		motor[rClaw] = PID_runtime(clawPID_R, SensorValue[pinchR]);
		motor[LClaw] = PID_runtime(clawPID_L, SensorValue[pinchL]);
	}
}
