#pragma config(Sensor, in1,    arm,            sensorPotentiometer)
#pragma config(Sensor, in2,    driveSelect,    sensorPotentiometer)
#pragma config(Sensor, in3,    pinchL,         sensorPotentiometer)
#pragma config(Sensor, in4,    pinchR,         sensorPotentiometer)
#pragma config(Motor,  port1,           rDrive1,       tmotorVex393TurboSpeed_HBridge, openLoop)
#pragma config(Motor,  port2,           Lift1,         tmotorVex393TurboSpeed_MC29, openLoop)
#pragma config(Motor,  port3,           LDrive1,       tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port4,           LClaw,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           rDrive2,       tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           Lift2,         tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port7,           rClaw,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           LDrive2,       tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port9,           Lift3,         tmotorVex393TurboSpeed_MC29, openLoop)
#pragma config(Motor,  port10,          LDrive3,       tmotorVex393TurboSpeed_HBridge, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX2)

// Select Download method as "competition"
#pragma competitionControl(Competition)

//Main competition background code...do not modify!
#include "Vex_Competition_Includes.c"
#include "BackOver Functions.c"



void pre_auton() {	bStopTasksBetweenModes = true; }

task autonomous() {	AutonomousCodePlaceholderForTesting(); }

task usercontrol()
{
	////setting initial value for the Arm and Pinch
	pinchRRequestedValue = SensorValue[ pinchR ];
	pinchLRequestedValue = SensorValue[ pinchL ];


	//// start the PID task's

	startTask( pinchRController );
	startTask( pinchLController );


		motor[LDrive1] = vexRT[Ch2];
		motor[LDrive2] = vexRT[Ch2];
		motor[LDrive3] = vexRT[Ch2];
		motor[rDrive1] = vexRT[Ch3];
		motor[rDrive2] = vexRT[Ch3];



	while (true)
	{

		motor[LDrive1] = vexRT[Ch2];
		motor[LDrive2] = vexRT[Ch2];
		motor[LDrive3] = vexRT[Ch2];
		motor[rDrive1] = vexRT[Ch3];
		motor[rDrive2] = vexRT[Ch3];


		///// lift control /////////////////////////////////////////////////////////////////
	int liftStillSpeedSet;

		if( vexRT[Btn5D] == 1 )
		{
			motor[Lift1] = 127;
			motor[Lift2] = 127;
			motor[Lift3] = 127;
		//	motor[Lift4] = 127;
		//	motor[Lift5] = 127;
			liftStillSpeedSet=15;
		}

		else if( vexRT[Btn5U] == 1 )
		{
			motor[Lift1] = -127;
			motor[Lift2] = -127;
			motor[Lift3] = -127;
		//	motor[Lift4] = -127;
		//	motor[Lift5] = -127;
			liftStillSpeedSet=-15;
		}

		else
		{
			motor[Lift1] = liftStillSpeedSet;
			motor[Lift2] = liftStillSpeedSet;
			motor[Lift3] = liftStillSpeedSet;
		//	motor[Lift4] = liftStillSpeedSet;
		//	motor[Lift5] = liftStillSpeedSet;
		}

		//// pinch control /////////////////////////////////////////////////////////////////////////////////

		if( vexRT[ Btn6D ] == 1 )
		{
			pinchRRequestedValue = 400;
			pinchLRequestedValue = 400;
		}

		else if( vexRT[ Btn6U ] == 1)
		{
			pinchRRequestedValue = 1150;
			pinchLRequestedValue = 1150;
		}
		else if(vexRT[Btn7D] == 1)
		{
			pinchRRequestedValue = 2000;
			pinchLRequestedValue = 2000;
		}


		wait1Msec(50);

	}
}
